package terraform.spotify.lambda.poc.handler

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent
import terraform.spotify.lambda.poc.construction.ObjectConstructor


class LambdaHandler : RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {
    val objectConstructor = ObjectConstructor()
    val lineBotHookController = objectConstructor.lineBotHookController

    override fun handleRequest(input: APIGatewayProxyRequestEvent, context: Context): APIGatewayProxyResponseEvent {
        val logger = context.logger

        logger.log("------")
        logger.log("input: $input")
        val inputBody = input.body
        logger.log("------")
        logger.log("[debug] body: $inputBody")

        return if (input.path == "/callback") {
            // LINE BOT のハンドラ
            lineBotHookController.handle(input, context)
        } else if (input.path == "/test") {
            val headers = mapOf(
                "Content-Type" to "text/html"
            )
            APIGatewayProxyResponseEvent().apply {
                isBase64Encoded = false
                statusCode = 200
                setHeaders(headers)
                body = "<!DOCTYPE html><html><head><title>AWS Lambda sample</title></head><body>" +
                        "<h1>Welcome</h1><p>Page generated by a Lambda function.</p>" +
                        "</body></html>"
            }
        } else {
            val headers = mapOf(
                "Content-Type" to "text/html"
            )
            APIGatewayProxyResponseEvent().apply {
                isBase64Encoded = false
                statusCode = 404
                setHeaders(headers)
                body = "<!DOCTYPE html><html><head><title>Error</title></head><body>" +
                        "<h1>No such endpoint.</h1>" +
                        "</body></html>"
            }
        }
    }
}
