package terraform.spotify.lambda.poc.controller

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent
import terraform.spotify.lambda.poc.construction.ObjectConstructor
import terraform.spotify.lambda.poc.entity.AwsInputEvent
import terraform.spotify.lambda.poc.service.LineBotService

class LineBotHookController(
    val token: String,
    val objectConstructor: ObjectConstructor
) {
    val lineBotService = LineBotService(token)

    fun handle(inputEvent: AwsInputEvent, context: Context): APIGatewayProxyResponseEvent {
        val headers = mapOf(
            "Content-Type" to "text/html"
        )

        inputEvent.events.forEach {
            val message = "[received] ${it.message.text}"
            lineBotService.replyToMessage(it.replyToken, message)
        }
        // assert 入れたい
        val text = inputEvent.events[0].message.text

        val head = text.split(" ")[0]
        val bodyValue = text.split(" ")[1]
        when (head) {
            "register-refresh" -> {

            }
            "register-playlist" -> {
                val userId = inputEvent.events[0].source.userId
                objectConstructor.spotifyService.registerNewPlaylistId(userId, bodyValue, context.logger)
            }
            "add-to-playlist" -> ""
        }
        return APIGatewayProxyResponseEvent().apply {
            isBase64Encoded = false
            statusCode = 200
            setHeaders(headers)
            body = "<!DOCTYPE html><html><head><title>AWS Lambda sample</title></head><body>" +
                    "<h1>Welcome</h1><p>Page generated by a Lambda function.[LineBotHookController]</p>" +
                    "</body></html>"
        }
    }

}